#ifndef DODEE_STATUS_CODES_H
#define DODEE_STATUS_CODES_H

typedef int DodeeStatus;

// Generic status codes
#define DODEE_SUCCESS  0
#define DODEE_FAILURE  1

// Errors
#define DODEE_ERROR_INVALID_ARGUMENT 2
#define DODEE_ERROR_NULL_ARGUMENT 3
#define DODEE_ERROR_BUFFER_OVERFLOW 4
#define DODEE_ERROR_NOT_IMPLEMENTED 5
#define DODEE_ERROR_FILE_NOT_FOUND 6
#define DODEE_ERROR_CONFIG_FORMAT 7
#define DODEE_ERROR_ALLOCATION_FAILED 8
#define DODEE_ERROR_PERMISSION_DENIED 9
#define DODEE_ERROR_FORK_FAILED 11

// Warnings
#define DODEE_WARNING_NO_TASKS 12

#endif /* DODEE_STATUS_CODES_H */
