#ifndef PASTA_ERROR_H
#define PASTA_ERROR_H

typedef int Status;

#define PASTA_SUCCESS  0
#define PASTA_FAILURE  1
#define PASTA_ERROR_INVALID_ARGUMENT 2
#define PASTA_ERROR_NULL_ARGUMENT 3
#define PASTA_ERROR_BUFFER_OVERFLOW 4
#define PASTA_ERROR_INVALID_SYNTAX 5
#define PASTA_ERROR_MALLOC_FAIL 6
#define PASTA_ERROR_NOT_IMPLEMENTED 7

#endif /* PASTA_ERROR_H */
