#ifndef PASTA_ERROR_H
#define PASTA_ERROR_H

typedef int Status;

// Generic status codes
#define PASTA_SUCCESS  0
#define PASTA_FAILURE  1

// Errors
#define PASTA_ERROR_INVALID_ARGUMENT 2
#define PASTA_ERROR_NULL_ARGUMENT 3
#define PASTA_ERROR_BUFFER_OVERFLOW 4
#define PASTA_ERROR_INVALID_SYNTAX 5
#define PASTA_ERROR_NOT_IMPLEMENTED 6
#define PASTA_ERROR_FILE_NOT_FOUND 7
#define PASTA_ERROR_CONFIG_FORMAT 8
#define PASTA_ERROR_ALLOCATION_FAILED 9
#define PASTA_ERROR_PERMISSION_DENIED 10

// Warnings
#define PASTA_WARNING_NO_MODULES 11

#endif /* PASTA_ERROR_H */
